cat_to_run:
#  - "CONF._REGALO_VINI_E_SPUMANTI"
#  - "ACCESSORI_CASA_VARI"
#  - "PET_SERVIZI"
#  - "BIRRE_CONFEZIONE_REGALO"
#  - "COLORANTI_CAPELLI_UOMO"
#  - "ACCESSORI_VARI_PULIZIA_CASA"
#  - "SERVIZI_E_-_COMM"
#  - "CONF.REGALO_PROFUMERIA"
#  - "LIQUORI_CONFEZIONE_REGALO"
#  - "SMACCHIATORI"
#  - "PRODOTTI_PER_PIEDI"
#  - "CREME_VISO_E_PROFUMI_UOMO"
#  - "SPAZZOLE_ABITI"
#  - "PREPARATI_DEL_LATTE"
#  - "CARNI_SURGELATE"
#  - "CAMBIO_STAGIONE"
#  - "PRODOTTI_EQUO_E_SOLIDALI"
#  - "PRODOTTI_CALZATURE_/PELLI"
#  - "SHOPPER_RIUTILIZZABILI"
#  - "SCIROPPI"
#  - "PRODOTTI_SOLARI"
#  - "SUCCO_DI_LIMONE"
#  - "VINI_LIQUOROSI"
#  - "PREPARATI_ALIMENTARI_VARI"
#  - "APPRETTI_/_ACQUA__DISTILLATA"
#  - "STUZZICADENTI/SPIEDINI"
#  - "PRODOTTI_BELLEZZA_GENERICI"
#  - "CACAO"
#  - "DEODORANTE_UOMO"
#  - "PET_CARE"
#  - "PANNOLINI_PER_BAMBINI"
#  - "PRODOTTI_PER_BARBA"
#  - "ALTRE_RICORRENZE/CONF_REGALO"
#  - "CREME_MANI_UNGHIE_/_DEPILAZION"
#  - "FRUTTA_SCIROPPATA"
#  - "APERITIVI_ANALCOLICI"
#  - "PIATTI_ETNICI"
#  - "PRODOTTI_BELLEZZA_COSMETICI"
#  - "SALUTISTICI"
#  - "ANTITARMICI"
#  - "PANNOLINI_PER_INCONTINENTI"
#  - "PREPARATI_PER_BEVANDE"
#  - "PANNI_PULIZIA_CASA"
#  - "RASATURA"
#  - "GUANTI"
#  - "DEODORANTI_AMBIENTE"
#  - "IGIENE_BABY"
#  - "INSETTICIDI/REPELLENTI"
#  - "IGIENE_INTIMA"
#  - "ALTRI_PROD.SURGELATI"
#  - "CREME_VISO_E_PROFUMI_DONNA"
#  - "SNACK_BENESSERE"
#  - "PET_MIX_-_LETTIERA"
#  - "SPUGNE_E_PANNI"
#  - "DEODORANTI_DONNA"
#  - "SCOPE_E_SPAZZOLONI"
#  - "RICORRENZE_PASQUA"
#  - "SNACK_SURGELATI"
#  - "SACCHI_NETTEZZA"
#  - "ACETO"
#  - "FAZZOLETTI_DI_CARTA_/_VELINE"
#  - "DROGHE"
#  - "SPUMANTI"
#  - "VINI_PASTO"
#  - "GALLETTE"
#  - "TOVAGLIOLI_DI_CARTA"
#  - "PREPARATI_PER_BRODO"
#  - "LIQUORI"
#  - "RICORRENZE_NATALE"
#  - "ALIMENTI_INFANZIA"
#  - "SALE"
#  - "PASTICCERIA_INDUSTRIALE"
#  - "DETERSIVO_LAVATRICE"
#  - "SALUMI_TAKE_AWAY_LS"
#  - "ASSORBENTI_IGIENICI"
#  - "USA_E_GETTA"
#  - "ADDITIVI_/CANDEGGINE"
#  - "OLIO_DI_SEMI"
#  - "AMMORBITENTI_/_BUCATO_A_MANO"
#  - "PIATTI_PRONTI_SURGELATI"
#  - "PASTA_ALL'UOVO"
#  - "VINI_BRIK"
#  - "CONDIMENTI_PRONTI"
#  - "PIZZE_SURGELATE"
#  - "PRODOTTI_CAPELLI"
#  - "CEREALI_PRIMA_COLAZIONE"
#  - "DETERGENZA_CASA"
#  - "RISO"
#  - "PRECOTTI_LS"
#  - "ZUCCHERO"
#  - "OLIO_DI_OLIVA"
#  - "CONTENITORI_ALIMENTI"
#  - "CARTA_CASA"
#  - "FETTE_BISCOTTATE"
#  - "PESCE_SURGELATO"
#  - "DOLCI_FRESCHI_LS"
#  - "DETERSIVI_STOVIGLIE"
#  - "PROFUMERIA_CORPO"
#  - "CONDIMENTI_FRESCHI_LS"
#  - "IGIENE_ORALE"
#  - "SALSE_E_AFFINI"
#  - "PREPARATI_PER_DOLCI"
#  - "CARTA_IGIENICA"
#  - "SURROGATI/INFUSI"
#  - "CONSERVE_LEGUMI"
#  - "FARINA"
#  - "ACQUA_PICCOLA"
#  - "SOTTOLI__E_SOTTACETI"
#  - "PIATTI_PRONTI_LS"
#  - "PET-DOG"
#  - "SACCHETTI_BIO"
#  - "BISCOTTI_RICOPERTI"
#  - "CARAMELLE/_CHEWING_GUM"
#  - "VINO_CANTINETTA"
#  - "ALTRI_PROD.FRESCHI_LS"
#  - "PASTA_FRESCA_LS"
#  - "MINESTRE_PREPARATE/FUNGHI_SECC"
#  - "CAFFE'"
#  - "SPALMABILI_DOLCI"
#  - "DETERGENTI_BAGNO_WC"
#  - "VEGETALI_SURGELATI"
#  - "SOSTITUTIVI_PANE"
#  - "CONSERVE_ROSSE"
#  - "GELATI"
#  - "CONSERVE_ANIMALI"
#  - "SUCCHI_E_NETTARI"
#  - "SNACK_SALATI"
#  - "UOVA_FRESCHE"
#  - "PANI_MORBIDI"
#  - "BIRRE"
#  - "MERENDINE"
#  - "PARAFARMACIA_GV"
#  - "CIOCCOLATO_/_SPECIALITA'_DOLCI"
#  - "PET-CAT"
#  - "LATTE_E_PANNA_FRESCHI_LS"
#  - "ACQUA"
#  - "BISCOTTI"
  - "BIBITE"
  - "SALUMI_LS"
  - "LATTICINI_UHT"
  - "SHOPPER_CASSA"
  - "YOGURT_LS"
  - "PASTA_DI_SEMOLA"
  - "FORMAGGI_LS"
cat_to_run_all:
  - "CONF._REGALO_VINI_E_SPUMANTI"
  - "ACCESSORI_CASA_VARI"
  - "PET_SERVIZI"
  - "BIRRE_CONFEZIONE_REGALO"
  - "COLORANTI_CAPELLI_UOMO"
  - "ACCESSORI_VARI_PULIZIA_CASA"
  - "SERVIZI_E_-_COMM"
  - "CONF.REGALO_PROFUMERIA"
  - "LIQUORI_CONFEZIONE_REGALO"
  - "SMACCHIATORI"
  - "PRODOTTI_PER_PIEDI"
  - "CREME_VISO_E_PROFUMI_UOMO"
  - "SPAZZOLE_ABITI"
  - "PREPARATI_DEL_LATTE"
  - "CARNI_SURGELATE"
  - "CAMBIO_STAGIONE"
  - "PRODOTTI_EQUO_E_SOLIDALI"
  - "PRODOTTI_CALZATURE_/PELLI"
  - "SHOPPER_RIUTILIZZABILI"
  - "SCIROPPI"
  - "PRODOTTI_SOLARI"
  - "SUCCO_DI_LIMONE"
  - "VINI_LIQUOROSI"
  - "PREPARATI_ALIMENTARI_VARI"
  - "APPRETTI_/_ACQUA__DISTILLATA"
  - "STUZZICADENTI/SPIEDINI"
  - "PRODOTTI_BELLEZZA_GENERICI"
  - "CACAO"
  - "DEODORANTE_UOMO"
  - "PET_CARE"
  - "PANNOLINI_PER_BAMBINI"
  - "PRODOTTI_PER_BARBA"
  - "ALTRE_RICORRENZE/CONF_REGALO"
  - "CREME_MANI_UNGHIE_/_DEPILAZION"
  - "FRUTTA_SCIROPPATA"
  - "APERITIVI_ANALCOLICI"
  - "PIATTI_ETNICI"
  - "PRODOTTI_BELLEZZA_COSMETICI"
  - "SALUTISTICI"
  - "ANTITARMICI"
  - "PANNOLINI_PER_INCONTINENTI"
  - "PREPARATI_PER_BEVANDE"
  - "PANNI_PULIZIA_CASA"
  - "RASATURA"
  - "GUANTI"
  - "DEODORANTI_AMBIENTE"
  - "IGIENE_BABY"
  - "INSETTICIDI/REPELLENTI"
  - "IGIENE_INTIMA"
  - "ALTRI_PROD.SURGELATI"
  - "CREME_VISO_E_PROFUMI_DONNA"
  - "SNACK_BENESSERE"
  - "PET_MIX_-_LETTIERA"
  - "SPUGNE_E_PANNI"
  - "DEODORANTI_DONNA"
  - "SCOPE_E_SPAZZOLONI"
  - "RICORRENZE_PASQUA"
  - "SNACK_SURGELATI"
  - "SACCHI_NETTEZZA"
  - "ACETO"
  - "FAZZOLETTI_DI_CARTA_/_VELINE"
  - "DROGHE"
  - "SPUMANTI"
  - "VINI_PASTO"
  - "GALLETTE"
  - "TOVAGLIOLI_DI_CARTA"
  - "PREPARATI_PER_BRODO"
  - "LIQUORI"
  - "RICORRENZE_NATALE"
  - "ALIMENTI_INFANZIA"
  - "SALE"
  - "PASTICCERIA_INDUSTRIALE"
  - "DETERSIVO_LAVATRICE"
  - "SALUMI_TAKE_AWAY_LS"
  - "ASSORBENTI_IGIENICI"
  - "USA_E_GETTA"
  - "ADDITIVI_/CANDEGGINE"
  - "OLIO_DI_SEMI"
  - "AMMORBITENTI_/_BUCATO_A_MANO"
  - "PIATTI_PRONTI_SURGELATI"
  - "PASTA_ALL'UOVO"
  - "VINI_BRIK"
  - "CONDIMENTI_PRONTI"
  - "PIZZE_SURGELATE"
  - "PRODOTTI_CAPELLI"
  - "CEREALI_PRIMA_COLAZIONE"
  - "DETERGENZA_CASA"
  - "RISO"
  - "PRECOTTI_LS"
  - "ZUCCHERO"
  - "OLIO_DI_OLIVA"
  - "CONTENITORI_ALIMENTI"
  - "CARTA_CASA"
  - "FETTE_BISCOTTATE"
  - "PESCE_SURGELATO"
  - "DOLCI_FRESCHI_LS"
  - "DETERSIVI_STOVIGLIE"
  - "PROFUMERIA_CORPO"
  - "CONDIMENTI_FRESCHI_LS"
  - "IGIENE_ORALE"
  - "SALSE_E_AFFINI"
  - "PREPARATI_PER_DOLCI"
  - "CARTA_IGIENICA"
  - "SURROGATI/INFUSI"
  - "CONSERVE_LEGUMI"
  - "FARINA"
  - "ACQUA_PICCOLA"
  - "SOTTOLI__E_SOTTACETI"
  - "PIATTI_PRONTI_LS"
  - "PET-DOG"
  - "SACCHETTI_BIO"
  - "BISCOTTI_RICOPERTI"
  - "CARAMELLE/_CHEWING_GUM"
  - "VINO_CANTINETTA"
  - "ALTRI_PROD.FRESCHI_LS"
  - "PASTA_FRESCA_LS"
  - "MINESTRE_PREPARATE/FUNGHI_SECC"
  - "CAFFE'"
  - "SPALMABILI_DOLCI"
  - "DETERGENTI_BAGNO_WC"
  - "VEGETALI_SURGELATI"
  - "SOSTITUTIVI_PANE"
  - "CONSERVE_ROSSE"
  - "GELATI"
  - "CONSERVE_ANIMALI"
  - "SUCCHI_E_NETTARI"
  - "SNACK_SALATI"
  - "UOVA_FRESCHE"
  - "PANI_MORBIDI"
  - "BIRRE"
  - "MERENDINE"
  #- "PARAFARMACIA_GV"
  - "CIOCCOLATO_/_SPECIALITA'_DOLCI"
  - "PET-CAT"
  - "LATTE_E_PANNA_FRESCHI_LS"
  - "ACQUA"
  - "BISCOTTI"
  - "BIBITE"
  - "SALUMI_LS"
  - "LATTICINI_UHT"
  #- "SHOPPER_CASSA"
  - "YOGURT_LS"
  - "PASTA_DI_SEMOLA"
  - "FORMAGGI_LS"
